### ISSUE TITLE
RPM and CSV export

### ISSUE THREAD

**Issue by Spyrogif** [Benny121221/AssettoCorsaTelemetryApp#24]
**Describe the bug**
CSV export : RPM data are missing

**To Reproduce**
Export any session to Csv 

**Expected behavior**
Records Rpm to Csv as others data

**Screenshots**
You can check an CSV Example here.
[2021-05-05 08h39m25Z (UTC) ACTelemetry.csv](https://github.com/bclehmann/ACTelemetry/files/6426107/2021-05-05.08h39m25Z.UTC.ACTelemetry.csv)

**System Information:**
- OS: [e.g. Windows 10]
- Release [e.g. 1.1.2]
- OS Architecture [e.g. 64 Bit]
- .NET Core Runtime version [e.g. 3.1]

If you don't know the answer to one of these questions I will be able to walk you through finding the answer.

**Additional context**

**Comment by Spyrogif** [comment]
I could be wrong but  no mention about RPM inside https://github.com/bclehmann/ACTelemetry/blob/master/WPFApp/MainWindow.xaml.cs  at line 545

**Comment by bclehmann** [comment]
Addressed in 1.5.2.

Thank you for pointing this out to me, and apologies for the slow response. I've been busy with work.
